EmployeeManagement/urls.py
from django.contrib import admin
from django.urls import path
from employees import views
from django.conf import settings
from django.conf.urls.static import static
from employees.views import emp, show, edit, update, details, destroy
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', emp.as_view()),  
    path('emp', emp.as_view()),  
    path('show', show.as_view()),  
    path('edit/<int:id>', edit.as_view()),  
    path('update/<int:id>', update.as_view()),  
    path('delete/<int:id>', destroy.as_view()), 
    path('details/<int:id>', details.as_view()),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/models.py
from django.db import models
from django import forms
import datetime

# Create your models here.
class Employee(models.Model):  
    CATEGORY_CHOICES= [
    ('HR Management Software', 'HR Management Software'),
    ('Cloud & SaaS', 'Cloud & SaaS'),
    ('CMMS Software', 'CMMS Software'),
    ('Telecomm Management', 'Telecommunications Management'),
    ('ERP Software', 'ERP Software')
    ]
    gender = (('Male','MALE'),
         ('Female','FEMALE'),)
    profile_pic = models.ImageField(upload_to='images/',default="")
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=10) 
    experience = models.IntegerField(default='0')
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES, null=True) 
    address = models.TextField(default="null")
    dob = models.CharField(max_length=100)
    checkgender = models.CharField(max_length=15,choices=gender, default='M')
    nationality =  models.BooleanField()
    salary = models.FloatField(default='00.00')
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    class Meta:  
        db_table = "employee"

employees/forms.py
from django import forms  
from employees.models import Employee 

class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__" 
        widgets = {
            'checkgender': forms.RadioSelect(),
        }
       

employees/views.py
from django.shortcuts import render, redirect  
from employees.forms import EmployeeForm  
from employees.models import Employee  
from django.views import View
# Create your views here.  
class emp(View):
    def post(self, request):  
        if request.method == "POST":  
            form = EmployeeForm(request.POST, request.FILES)   
            if form.is_valid():  
                try:  
                    form.save() 
                    return redirect('/show')  
                except:  
                    pass  
        else:  
            form = EmployeeForm()  
            return render(request,'index.html',{'form':form}) 
    def get(self, request):  
        if request.method == "POST":  
            form = EmployeeForm(request.POST, request.FILES)   
            if form.is_valid():  
                try:  
                    form.save() 
                    return redirect('/show')  
                except:  
                    pass  
        else:  
            form = EmployeeForm()  
            return render(request,'index.html',{'form':form}) 
class show(View):
    def get(self, request):  
        employees = Employee.objects.all()  
        return render(request,"show.html",{'employees':employees})  
class edit(View):
    def get(self, request, id):  
        employee = Employee.objects.get(id=id)  
        return render(request,'edit.html', {'employee':employee}) 
class update(View):
    def post(self, request, id):  
        employee = Employee.objects.get(id=id)  
        form = EmployeeForm(request.POST, request.FILES, instance = employee) 
        if form.is_valid(): 
            form.save() 
            return redirect("/show")  
        {{form.error_class}}
        return render(request, 'edit.html', {'employee': employee})  
class details(View):
    def get(self, request, id):
        employee = Employee.objects.get(id=id)  
        return render(request, 'details.html', {'employee': employee}) 
class destroy(View):
    def get(self, request, id):  
        employee = Employee.objects.get(id=id)  
        employee.delete()  
        return redirect("/show")  

employees/templates/details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/profilestyle.css' %}">
</head>
<!------ Include the above in your HEAD tag ---------->

<body>
    <div class="container emp-profile">
        <form method="post" class="post-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <div class="profile-img">
                        <img style="border-radius: 5%;" src="{{employee.profile_pic.url}} " alt="">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="profile-head">
                        <h5>
                            {{employee.ename}}
                        </h5>
                        <h6>
                            {{employee.category}}
                        </h6>
                        <p class="proile-rating">EXPERIENCE : <span>{{employee.experience}} years</span></p>
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                    aria-controls="home" aria-selected="true">About</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-2">
                    <p>Updated on {{employee.updated_at}} &ensp;</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="profile-work">
                        <p>DATE OF BIRTH</p>
                        <a href="">&ensp; {{employee.dob}}</a>
                        <p>NATIONALITY</p>
                            {% if employee.nationality == True %}
                                <a href="">&ensp; Indian </a>
                            {% else %}
                                <a href="">&ensp; Non-Indian</a>
                            {% endif %}

                        <p>GENDER</p>
                        <a href="">&ensp; {{employee.checkgender}}</a>
                        <p>CREATED ON</p>
                        <a href="">&ensp; {{employee.created_at}}</a>

                    </div>
                </div>

                <div class="col-md-8">
                    <div class="tab-content profile-tab" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>User Id</label>
                                </div>
                                <div class="col-md-6">
                                    <p>{{employee.eid}}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Name</label>
                                </div>
                                <div class="col-md-6">
                                    <p>{{employee.ename}} </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Email</label>
                                </div>
                                <div class="col-md-6">
                                    <p>{{employee.eemail}} </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Phone</label>
                                </div>
                                <div class="col-md-6">
                                    <p>{{employee.econtact}}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Profession</label>
                                </div>
                                <div class="col-md-6">
                                    <p>{{employee.category}} </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Address</label>
                                </div>
                                <div class="col-md-6">
                                    <p>{{employee.address}} </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Salary</label>
                                </div>
                                <div class="col-md-6">
                                    <p>Rs {{employee.salary}} </p>
                                </div>
                            </div>
                        </div>
                        <!--                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Experience</label>
                                </div>
                                <div class="col-md-6">
                                    <p>Expert</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Hourly Rate</label>
                                </div>
                                <div class="col-md-6">
                                    <p>10$/hr</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Total Projects</label>
                                </div>
                                <div class="col-md-6">
                                    <p>230</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Registered on Database</label>
                                </div>
                                <div class="col-md-6">
                                    <p>{{employee.created_at}}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Availability</label>
                                </div>
                                <div class="col-md-6">
                                    <p>6 months</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label>Address</label><br />
                                    <p>{{employee.address}} </p>
                                </div>
                            </div>
                        </div>
            -->
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>

</html>

employees/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Index</title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body style=" border: 10px solid rgb(252, 248, 7);">

  <form method="POST" class="post-form" action="/update/{{employee.id}}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Update Details</h3>

        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
          <input type="file" name="profile_pic" id="id_profile_pic" maxlength="20" value="{{ employee.profile_pic }}" />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
          <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}" />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Experience:</label>
        <div class="col-sm-4">
          <input type="text" name="experience" id="id_experience" value="{{ employee.experience }}" />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">
          <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee category:</label>
        <div class="col-sm-4">
          <select name="category" id="id_category">
            {% for i, k in employee.CATEGORY_CHOICES %}
            <option value="{{i}}">
              {{k}}
            </option>
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee DOB:</label>
        <div class="col-sm-4">
          <input type="date" name="dob" id="id_dob" value="{{ employee.dob }}" />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Address:</label>
        <div class="col-sm-4">
          <input type="text" name="address" id="id_address" value="{{ employee.address }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Salary:</label>
        <div class="col-sm-4">
          <input type="text" name="salary" id="id_salary" value="{{ employee.salary }}" />
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-4">
          <p>Previous entered value: &emsp; &emsp; &ensp;
            {{employee.checkgender}}</p>
          <input type="radio" name="checkgender" id="id_checkgender" maxlength="15" value="Male" />
          <label >MALE</label> <br>
          <input type="radio" name="checkgender" id="id_checkgender" maxlength="15" value="Female" />
          <label >FEMALE</label> <br>
          <br>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Indian: </label>
        <div class="col-sm-4">
          <input type="checkbox" name="nationality" id="id_nationality" value="True" />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-success">Update</button>
        
        </div>
      </div>
    </div>
  </form>
</body>

</html>

employees/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Index</title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body style="background-color: rgb(248, 184, 160);
 border: 10px solid rgb(7, 235, 252);">
  <form method="POST" class="post-form" action="/emp" enctype="multipart/form-data">
    {% csrf_token %}
    <div  " class="container">
      <br>
      <div class="form-group row">
        <label class="label label-info"></label>
        <div style="text-align:center" class="col-sm-4">
          <h3 s>Enter Details</h3>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Image:</label>
        <div class="col-sm-4">
          {{form.profile_pic}}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label" >Employee Id:</label>
        <div class="col-sm-4">
          {{ form.eid }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Indian: </label>
        <div class="col-sm-4">
          {{ form.nationality }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label" >Employee Salary:</label>
        <div class="col-sm-4" style="box-sizing: inherit;">
          {{ form.salary }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Experience:</label>
        <div class="col-sm-4">
          {{ form.experience }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          {{ form.ename }}
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          {{ form.eemail }}
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">
          {{ form.econtact }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Category:</label>
        <div class="col-sm-4">
          {{ form.category }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee DOB:</label>
        <div class="col-sm-4">
          <input type="date" name="dob" id="id_dob" value="{{employee.dob}} ">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee address:</label>
        <div class="col-sm-4">
          {{ form.address }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Gender:</label>
        <div class="col-sm-4">
          {{ form.checkgender }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </div>
  </form>
</body>

</html>

employees/templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <!-- As a heading -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">EMPLOYEES RECORDS</span>
           
        </div>
    </nav>
</head>

<body>

    <table class="table table-striped table-bordered table-sm">
        <thead class="thead-dark">
            <tr>
                <th>Image</th>
                <th>ID</th>
                <th> Name</th>
                <th> Email</th>
                <th> Contact</th>
                <th>Profession Category</th>
                <th>Indian</th>
                <th>Gender</th>
                <th>Created</th>
                <th>Updated</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>
                <td> <img style="border-radius: 50%;" width="30" height="30" src="{{employee.profile_pic.url}} " alt="Employee Image">
                </td>
                <td>{{ employee.eid }}</td>
                <td>{{ employee.ename }}</td>
                <td>{{ employee.eemail }}</td>
                <td>{{ employee.econtact }}</td>
                <td>{{ employee.category}}</td>
                <td>{{employee.nationality}} </td>
                <td>{{employee.checkgender}} </td>
                <td>{{employee.created_at}} </td>
                <td>{{employee.updated_at}} </td>
                <td>
                    <a class="btn btn-outline-success" href="/details/{{ employee.id}} ">Info</a> <a class="btn btn-outline-warning" href="/edit/{{ employee.id }}">Edit</a>
                    <a class="btn btn-outline-danger" href="/delete/{{ employee.id }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <br>
    <center><a href="/emp" class="btn btn-primary"> + Add New </a></center>
</body>

</html>